/**
 * 
 */
package com.marcosbarbero.lab.sec.oauth.opaque.ds.web;

import java.security.Principal;

import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * A class that accept an OAuth token, that has been generated by a client_credentials grant type. As the client is
 * configured in the authorization server to have the <I>ROLE_CLIENT</I> role, we configure Spring Security based on
 * this value.
 * 
 * @author etienne-sf
 */
@RestController
@RequestMapping("/api")
public class HelloClientController {

	@GetMapping
	@PreAuthorize("hasRole('ROLE_CLIENT')")
	public ResponseEntity<String> get(final Principal principal) {
		return ResponseEntity.ok("Hello, client!");
	}

}
